// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5En2x4SkwofivzkZ49Z6uxzIeQuquHqI',
    appId: '1:384399835177:web:9fdbe2c9b3a69dc9e61c38',
    messagingSenderId: '384399835177',
    projectId: 'fixit-7efd1',
    authDomain: 'fixit-7efd1.firebaseapp.com',
    storageBucket: 'fixit-7efd1.appspot.com',
    measurementId: 'G-SVFSPCEG42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzlO6I-HJEL-Q8KS8TXP_kqayd5P_byC0',
    appId: '1:384399835177:android:df404851ecdaa342e61c38',
    messagingSenderId: '384399835177',
    projectId: 'fixit-7efd1',
    storageBucket: 'fixit-7efd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7TBs1q3SFrAJ3Hnj6VvQu08KXx-XBxNg',
    appId: '1:384399835177:ios:f69b116e50602734e61c38',
    messagingSenderId: '384399835177',
    projectId: 'fixit-7efd1',
    storageBucket: 'fixit-7efd1.appspot.com',
    iosClientId: '384399835177-qjpeavlonc63lncae029tf1lkfi4jkm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7TBs1q3SFrAJ3Hnj6VvQu08KXx-XBxNg',
    appId: '1:384399835177:ios:f69b116e50602734e61c38',
    messagingSenderId: '384399835177',
    projectId: 'fixit-7efd1',
    storageBucket: 'fixit-7efd1.appspot.com',
    iosClientId: '384399835177-qjpeavlonc63lncae029tf1lkfi4jkm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitChallenge',
  );
}
